class GameConstants:
    # game rule
    ATTEMPTS_MIN = 1
    SEQUENCE_LENGTH_MIN = 1
    POOL_LENGTH_MIN = 2
    HARD_MODE_ATTEMPTS_AMOUNT = 4
    EASY_MODE_ATTEMPTS_AMOUNT = 6
    NAME_LENGTH_MAX = 20
    EASY_MODE_SEQUENCE_LENGTH = 4
    HARD_MODE_SEQUENCE_LENGTH = 6
    POOL_CUSTOMIZATION_NUMBER_OF_INPUT_EXPECTED = 2

    # score modified
    POOL_LENGTH_SCORE_MODIFIER = 2
    SEQUENCE_LENGTH_SCORE_MODIFIER = 3
    ALLOW_DUPLICATES_SCORE_MODIFIER = 1.5
    LESS_ATTEMPT_MODIFER = 2
    MORE_ATTEMPT_MODIFER = 0.75
    LESS_SEQUENCE_LENGTH_MODIFIER = 2
    SAME_SEQUENCE_LENGTH_MODIFIER = 0.5
    MORE_SEQUENCE_LENGTH_MODIFIER = 1.5
    WIN_AND_LESS_THAN_AI = 100

class GameStages:
    STARTING = 0
    CUSTOMIZING = 1
    PLAYING = 2
    ENDING = 3

class GameResult:
    # output
    CORRECT = 'correct'
    PARTIAL = 'partial'
    WRONG = 'wrong' 

    # result
    WINNER_CODEBREAKER = 'codebreaker'
    WINNER_MASTERMIND = 'mastermind'

class GameOptionMapping:
    END_POOL_OPTION = 'd'
    CLEAR_OPTION = 'c'
    QUIT_OPTION = 'q'
    START_OPTION = 's'
    DESCRIPTION_OPTION = 'd'
    STARTING_OPTIONS = [START_OPTION, DESCRIPTION_OPTION]
    ENDING_RECUSTOMIZE_OPTION = 'r'
    POOL_SINGLE_INPUT_SHOW_AVALIABLE_OPTION = 'a'
    POOL_SINGLE_INPUT_WILD_CARD_EXP_OPTION = 'v'

    EASY_PRESET_OPTION = 'e'
    EASY_PRESET = 'easy'
    HARD_PRESET_OPTION = 'h'
    HARD_PRESET = 'hard'
    CUTSTOM_MODE_OPTION = 'c'
    CUTSTOM_MODE = 'custom'

    ALLOW_DUPLICATE_TRUE_OPTION = 'y'
    ALLOW_DUPLICATE_FALSE_OPTION = 'n'

    HUMAN_BRAIN_OPTION = 'h'
    HUMAN = 'human'
    COMPUTER_BRAIN_OPTION = 'c'
    COMPUTER = 'computer'
    COMPUTER_CODEBREAKER_NAME = 'B0†'

    WILD_CARD_OPTION = 'all'

    CUSTOMIZING_MODE_MAPPING = {
        EASY_PRESET_OPTION:EASY_PRESET,
        HARD_PRESET_OPTION:HARD_PRESET,
        CUTSTOM_MODE_OPTION:CUTSTOM_MODE
    }

    CUSTOMIZING_ALLOW_DUPLICATES_MAPPING = {
        ALLOW_DUPLICATE_TRUE_OPTION:True,
        ALLOW_DUPLICATE_FALSE_OPTION:False
    }

    SEQUENCE_LENGTH_MAPPING = {
        EASY_PRESET:GameConstants.EASY_MODE_SEQUENCE_LENGTH,
        HARD_PRESET:GameConstants.HARD_MODE_SEQUENCE_LENGTH
    }
    
    CUSTOMIZING_BRAIN_MAPPING = {
        COMPUTER_BRAIN_OPTION:COMPUTER,
        HUMAN_BRAIN_OPTION:HUMAN
    }
    
    MODE_ATTEMPTS_MAPPING = {
        EASY_PRESET:GameConstants.EASY_MODE_ATTEMPTS_AMOUNT,
        HARD_PRESET:GameConstants.HARD_MODE_ATTEMPTS_AMOUNT
    }